collections:
  - microbits-intro
  - minecraft-clone
  - minecraft-pi
  - microbits-iot
  - projects
  - activities-minecraft:
      output: true
  - activities-microbit:
      output: true

presentation-theme: css/theme/white.css
