encoding: UTF-8

collections:
  microbits-intro:
    output: false
  minecraft-clone:
    output: false
  minecraft-pi:
    output: false
  microbits-iot:
    output: false
  projects:
    output: false
  activities-minecraft:
    output: true
  activities-microbit:
    output: true

url:  https://deejaygraham.github.io/makers-n-creators

presentation-theme: white
# syntax highlight themes from https://highlightjs.org/
syntax-theme: github
# monokai-sublime
# solarized-dark
# zenburn
