collections:
  microbits-intro:
    output: false
  minecraft-clone:
    output: false
  minecraft-pi:
    output: false
  microbits-iot:
    output: false
  projects:
    output: false
  activities-minecraft:
    output: true
  activities-microbit:
    output: true

url:  https://deejaygraham.github.io/makers-n-creators

presentation-theme: css/theme/white.css
syntax-theme: css/dracula.css
